# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: 'Kitchen Vagrant (FreeBSD)'
'on': ['push', 'pull_request']

env:
  KITCHEN_LOCAL_YAML: 'kitchen.vagrant.yml'

jobs:
  test:
    runs-on: 'macos-10.15'
    strategy:
      fail-fast: false
      matrix:
        instance:
          - default-freebsd-130-master-py3
          # - freebsd-130-master-py3
          - default-freebsd-123-master-py3
          # - freebsd-123-master-py3
          # - default-freebsd-130-3004-0-py3
          # - default-freebsd-123-3004-0-py3
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'
      - name: 'Set up Bundler cache'
        uses: 'actions/cache@v1'
        with:
          path: 'vendor/bundle'
          key: "${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"
          restore-keys: "${{ runner.os }}-gems-"
      - name: 'Run Bundler'
        run: |
          ruby --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: 'Run Test Kitchen'
        run: 'bundle exec kitchen verify ${{ matrix.instance }}'
